name: test-github-action

on:
    clone:
        branches: [main]
    push:
        branches: [main]
    pull_request:
        branches: [dev, hotfix, release, minor, major]
    issues:
        types: [opened, edited, reopened, assigned, unassigned, labeled, unlabeled]

jobs:
    git-action:
        name: