name: Github Action Testing yml

on: [push, fork]
run-name: Deployment CI/CD Testing ${{ inputs.sha }} by @${{ gituhb.actor }}

jobs:
    version:
    runs-on: ubuntu-latest
    steps:
        -
            uses: actions/checkout@v3