name: CI Testing Github Action

on:
  push:
    branches:
      - "main"

env:
  IMAGE_NAME: user/app

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name : Github Push and Commit
        uses : docker/build-push-action@v1