services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: choigunwoo/docker_test:a1.0.0
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

